# Generated by Django 3.0.8 on 2020-08-28 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JSSapp', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contect',
            new_name='content',
        ),
    ]
